<?xml version="1.0" encoding="UTF-8"?>
<!--
    NetBeans build file for the BoardingRoomFinder web project.
-->
<project name="BoardingRoomFinder" default="default" basedir=".">
    <description>Builds, tests, and runs the BoardingRoomFinder web project.</description>
    <import file="nbproject/build-impl.xml"/>
</project>
